services:
  server:
    build: .
    container_name: server
    command: ["server"]
    environment:
      SOCKET_PORT: ${SOCKET_PORT}
      PEER_SERVERS: "http://server2:8080,http://server3:8080"
      SERVER_ID: "server-a"
    ports:
      - "${SOCKET_PORT}:${SOCKET_PORT}"
      - "${REST_PORT}:8080"
    volumes:
        - ./data:/app/data