services:
  server:
    build: .
    container_name: server
    command: ["server"]
    environment:
      SOCKET_PORT: ${SOCKET_PORT}
      PEER_SERVER: ${PEER_SERVER}
      SERVER_ID: ${SERVER_ID}
    ports:
      - "${SOCKET_PORT}:${SOCKET_PORT}"
      - "${REST_PORT}:8080"
    volumes:
        - ./data:/app/data