services:

  client1:
    build: .
    container_name: client-1
    command: ["client"]
    environment:
      SERVER_IP: ${SERVER_IP}
      SOCKET_PORT: ${SOCKET_PORT}
    stdin_open: true
    tty: true